version: 2

sources:
  - name: raw
    quoting:
      database: true
      schema: true
      identifier: true
    schema: "pipedrive_data"
    tables:
      - name: persons
      - name: persons__email
      - name: persons__phone
