# put your secret values and credentials here. do not share this file and do not push it to github
[sources.pipedrive]
pipedrive_api_key = "api_secret_key" # please set me up!

[destination.bigquery.credentials]
project_id = "project_id" # please set me up!
private_key = "private_key" # please set me up!
client_email = "client_email" # please set me up!
location = "US"
